plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

group = 'com.claudeassistant'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.runelite.net'
    }
}

dependencies {
    compileOnly group: 'net.runelite', name: 'client', version: '1.10.+'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

shadowJar {
    archiveClassifier.set('')
}
